#!/bin/sh
cat >&2 <<'EOF'

  Write code
      ↓
  make test-be    ← unit tests backend
  make test-fe    ← unit tests frontend
  make test-e2e   ← end-to-end tests frontend
      ↓
  make fix-be     ← fix backend formatting + lint + mypy
  make fix-fe     ← fix frontend formatting + lint
      ↓
  make cicd-be    ← verify: pre-commit checks pass
  make cicd-fe    ← verify: pre-commit checks pass
      ↓
  git commit                                           ← you are here ←

EOF
